### ISSUE TITLE
Review of AOI-SpawnGarrison

### ISSUE THREAD

**Issue by 10Dozen** [Cambusta/Mercensurgency#8]
Please review

**Comment by Cambusta** [comment]
Reviewed, you're welcome. Тестировал на локалхосте и дедике.
- Маркеры все так же не работают в сингле.
- Кеширование работает очень хорошо, единственная проблема может быть максимум с инстант телепортами (из-за задержки).
- Зоны и юниты выбираются нормально, бартюни ходят кругами под сабатон, но техника не катается. Я понял, что это баг, а не фича, но вот из-за рандомного места спавна она иногда оказывается в бессмысленном месте, например, в лесу. Плюс стоящая на месте техника выглядит странновато.
- В домах народу - субъективно - маловато, почти нет, но это мелочь.
- ФПСы охуительные, вся эта радость съела всего 10 (60 > ~50).

**Comment by 10Dozen** [comment]
Ты в трелла пиши, тут я просто чтобы пнуть тебя. 
Ставь в трелле лейбл Reviewed и двигай тикеты которые можно коммитить

**Comment by Cambusta** [comment]
Done.
